name: Angular Dashboard CI

on:
  push:
    branches: [ develop, ci/workflows ]
  pull_request:
    branches: [ develop, ci/workflows ]

jobs:
  preflow:
    uses: ./.github/workflows/pre-job.yml

  lint:
    needs: preflow
    uses: ./.github/workflows/lint.yml
  
  unit-testing:
    needs: lint
    uses: ./.github/workflows/unit.yml
  
  e2e-testing:
    needs: unit-testing
    uses: ./.github/workflows/e2e.yml
