name: Unit Testing
on:
  workflow_call:

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup environment
        uses: ./.github/actions/setup-node

      - name: Run unit testing - Karma - Jasmine
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      
      - name: Confirm status
        run: |
          echo "✅ Unit Testing completed successfully"
          du -sh dist/* || true
          echo "🔹 Build branch: $GITHUB_REF_NAME"
          echo "🔹 Commit: $GITHUB_SHA"
          echo "🔹 Actor: $GITHUB_ACTOR"